In [1]:
import pandas as pd
import numpy as np

# Cargar el DataFrame desde el CSV
df = pd.read_csv('airbnb_gijonoviedo.csv')

In [4]:
# Rellenar ID vacío
df['ID'].fillna('sin_id', inplace=True)

# 1. Crear las columnas `Tipo de habitación` y `Título`
df['Tipo de habitación'] = df['Tipo de habitación'].str.split().str[0]
df['Título'] = df['Tipo de habitación'].str.split(':| en ', n=1).str[0]
df['Título'] = df['Título'].str.strip()

C:\Users\marco\AppData\Local\Temp\ipykernel_21556\1424143484.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['ID'].fillna('sin_id', inplace=True)

In [5]:
# 2. Transformar "No disponible" en nulos y eliminar el símbolo `€` en las columnas de precios
precios = ['Precio por noche Octubre', 'Precio por noche Agosto']
for columna in precios:
    if columna in df.columns:
        # Reemplazar "No disponible" y otras cadenas no numéricas por np.nan
        df[columna] = df[columna].replace(["No disponible", "No disponible en Octubre", "No disponible en Agosto"], np.nan)
        # Eliminar el símbolo € y otros caracteres no numéricos
        df[columna] = df[columna].replace(r'[^0-9]', '', regex=True).astype(float)

# 3. Transformar "sin valoraciones" y otros valores no numéricos en nulos en la columna de valoración
valores_no_numericos = ["Sin valoraciones", "Nuevo", "Sin evaluaciones"]
df['Valoración'] = df['Valoración'].replace(valores_no_numericos, np.nan)

# Asegurarse de que la columna es de tipo string antes de reemplazar comas
df['Valoración'] = df['Valoración'].astype(str)
df['Valoración'] = df['Valoración'].str.replace(',', '.').astype(float)

In [6]:
# 4. Dejar solo el número o los nulos en las columnas especificadas

#Definimos la funcion
def solo_numero(x):
    try:
        return int(x.split()[0])
    except (ValueError, AttributeError):
        return np.nan


df["Camas"]= df["Camas"].apply(solo_numero).astype('Int64')
df["Viajeros máximos"]= df["Viajeros máximos"].apply(solo_numero).astype('Int64')
df["Dormitorios"]= df["Dormitorios"].apply(solo_numero).astype('Int64')
df["Numero valoraciones"]= df["Numero valoraciones"].apply(solo_numero).astype('Int64')

def solo_numero_baño(x):
    try:
        return int(x.split()[0])
    except (ValueError, AttributeError):
        return 1
df["Baños"]= df["Baños"].apply(solo_numero_baño).astype('Int64')

In [7]:
df['Tipología'] = df['Tipo de habitación'].str.split().str[:1]
df["Tipología"]= df["Tipología"].astype(str).apply(lambda x: x.replace("['","").replace("']","").strip())

df['Precio Medio'] = df[['Precio por noche Agosto', 'Precio por noche Octubre']].mean(axis=1)
df['ID']= df['ID'].astype(str).str.zfill(18)

df = df.drop(df.filter(regex='Unnamed'), axis=1)

In [2]:
# Cargar el DataFrame desde el CSV
df = pd.read_csv('AsturiasDF_limpio_con_coordenadas.csv')

In [4]:
#Movemos las columnas para mejor visualización

df = df[['ID', 'Tipo de habitación', 'Título', 'Tipología', 'Ciudad', 'Localización', 'Precio por noche Agosto', 'Precio por noche Octubre', 'Precio Medio', 'Valoración', 'Numero valoraciones', 'Dormitorios', 'Baños', 'Camas', 'Viajeros máximos']]

In [6]:
# Guardar el DataFrame limpio en un nuevo CSV

df.to_csv('AsturiasDF_limpio_con_coordenadas.csv', index=False)

In [5]:
df.head(20)

,ID,Tipo de habitación,Título,Tipología,Ciudad,Localización,Precio por noche Agosto,Precio por noche Octubre,Precio Medio,Valoración,Numero valoraciones,Dormitorios,Baños,Camas,Viajeros máximos
0,970291990719745713,Alojamiento,Alojamiento,Alojamiento,Asturias,NaN,NaN,113.0,113.0,NaN,NaN,3.0,2,4.0,8.0
1,942548062721774719,Alojamiento,Alojamiento,Alojamiento,Asturias,NaN,NaN,82.0,82.0,NaN,NaN,2.0,5,2.0,4.0
2,870314109572136088,Alojamiento,Alojamiento,Alojamiento,Asturias,"43.5402,-5.6488",NaN,NaN,NaN,NaN,1.0,2.0,1,4.0,4.0
3,2612535,Alojamiento,Alojamiento,Alojamiento,Asturias,"43.54218,-5.66823",NaN,75.0,75.0,4.27,81.0,3.0,1,3.0,4.0
4,1068269463661698747,Alojamiento,Alojamiento,Alojamiento,Asturias,"43.568892,-5.72747",NaN,75.0,75.0,NaN,2.0,1.0,1,NaN,4.0
5,638312618652319673,Alojamiento,Alojamiento,Alojamiento,Asturias,"43.481,-5.4375",NaN,90.0,90.0,NaN,NaN,2.0,2,3.0,4.0
6,1093357909504048158,Alojamiento,Alojamiento,Alojamiento,Asturias,"43.3684,-5.8461",108.0,71.0,89.5,NaN,1.0,1.0,1,1.0,4.0
7,31712154,Alojamiento,Alojamiento,Alojamiento,Asturias,"43.53281,-5.6672",175.0,NaN,175.0,4.64,76.0,2.0,1,1.0,4.0
8,42293440,Alojamiento,Alojamiento,Alojamiento,Asturias,"43.25713,-5.86473",NaN,110.0,110.0,NaN,NaN,2.0,5,3.0,4.0
9,990475883858846733,Habitación,Habitación,Habitación,Asturias,"43.530766,-5.659302",NaN,43.0,43.0,4.60,10.0,1.0,1,2.0,NaN
10,1053054494400256201,Alojamiento,Alojamiento,Alojamiento,Asturias,"43.3746,-5.8528",NaN,50.0,50.0,4.17,6.0,1.0,1,1.0,2.0
11,50859290,Alojamiento,Alojamiento,Alojamiento,Asturias,"43.53762,-5.65225",NaN,96.0,96.0,4.75,16.0,3.0,2,5.0,6.0
12,1117913314795690350,Alojamiento,Alojamiento,Alojamiento,Asturias,"43.5407,-5.7037",NaN,57.0,57.0,NaN,NaN,3.0,1,4.0,6.0
13,602237136783911473,Alojamiento,Alojamiento,Alojamiento,Asturias,"43.5407,-5.6575",220.0,155.0,187.5,NaN,NaN,1.0,1,3.0,4.0
14,1075862665732287435,Alojamiento,Alojamiento,Alojamiento,Asturias,"43.368103,-5.85386",119.0,69.0,94.0,5.00,4.0,1.0,1,1.0,3.0
15,1050722557715613659,Alojamiento,Alojamiento,Alojamiento,Asturias,"43.5408,-5.6561",174.0,NaN,174.0,5.00,5.0,1.0,1,1.0,2.0
16,832606198985846218,Alojamiento,Alojamiento,Alojamiento,Asturias,"43.51865,-5.66447",NaN,NaN,NaN,4.81,16.0,3.0,2,4.0,6.0
17,53495435,Alojamiento,Alojamiento,Alojamiento,Asturias,"43.36344,-5.83299",NaN,54.0,54.0,NaN,NaN,1.0,1,3.0,4.0
18,2322671,Alojamiento,Alojamiento,Alojamiento,Asturias,"43.37869,-5.82981",NaN,55.0,55.0,4.66,99.0,1.0,1,1.0,2.0
19,20130888,Habitación,Habitación,Habitación,Asturias,"43.5428,-5.6661",75.0,49.0,62.0,4.70,87.0,2.0,1,1.0,NaN

In [123]:
# Guardar el DataFrame limpio en un nuevo CSV
df.to_csv('AsturiasDF_limpio.csv', index=False)